In [1]:
import pandas as pd
import numpy as np
import csv
from numpy.linalg import inv

In [2]:
##loading data
stock_2000 = pd.read_csv("nasdaq00.txt", header = None)[0].to_list()
stock_2001 = pd.read_csv("nasdaq01.txt", header = None)[0].to_list()

In [3]:
#Q1
X = []
Y = stock_2000[3:]
for i in range(len(stock_2000) - 3):
    X.append(stock_2000[i:i+3])
X = np.array(X)

A = np.zeros((3,3))
b = np.zeros(3)
for x in X:
    A += (np.matmul(np.matrix(x).T,np.matrix(x)))
for i in range(len(X)):
    b += np.dot(Y[i], X[i])
    
print(A)
print(b)

W = np.matmul(inv(A),b)
print("Coefficients =")
print(W)

[[3.65159733e+09 3.64553007e+09 3.64024608e+09]
 [3.64553007e+09 3.64300188e+09 3.63752268e+09]
 [3.64024608e+09 3.63752268e+09 3.63556951e+09]]
[3.63403032e+09 3.63120829e+09 3.62909744e+09]
Coefficients =
[0.03189569 0.01560133 0.95067337]


In [10]:
#Q2

predict_2000 = np.matmul(X,W)

X_2001 = []
for i in range(len(stock_2001) - 3):
    X_2001.append(stock_2001[i:i+3])
predict_2001 = np.matmul(X_2001,W)
Y_2001 = stock_2001[3:]
rmse_2000 = np.sqrt(((Y - predict_2000) ** 2).mean())
rmse_2001 = np.sqrt(((Y_2001 - predict_2001) ** 2).mean())
print("RMSE for 2000 = " + str(rmse_2000))
print("RMSE for 2001 = " + str(rmse_2001))

RMSE for 2000 = 117.90844361778286
RMSE for 2001 = 54.63604967519947
